/*
 * This file is generated by jOOQ.
 */
package io.micronaut.example.petclinic.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Pets implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private String        name;
    private LocalDate     birthDate;
    private Integer       typeId;
    private Integer       ownerId;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public Pets() {}

    public Pets(Pets value) {
        this.id = value.id;
        this.name = value.name;
        this.birthDate = value.birthDate;
        this.typeId = value.typeId;
        this.ownerId = value.ownerId;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public Pets(
        Integer       id,
        String        name,
        LocalDate     birthDate,
        Integer       typeId,
        Integer       ownerId,
        LocalDateTime createdAt,
        LocalDateTime updatedAt
    ) {
        this.id = id;
        this.name = name;
        this.birthDate = birthDate;
        this.typeId = typeId;
        this.ownerId = ownerId;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>public.pets.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.pets.id</code>.
     */
    public Pets setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.pets.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.pets.name</code>.
     */
    public Pets setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>public.pets.birth_date</code>.
     */
    public LocalDate getBirthDate() {
        return this.birthDate;
    }

    /**
     * Setter for <code>public.pets.birth_date</code>.
     */
    public Pets setBirthDate(LocalDate birthDate) {
        this.birthDate = birthDate;
        return this;
    }

    /**
     * Getter for <code>public.pets.type_id</code>.
     */
    public Integer getTypeId() {
        return this.typeId;
    }

    /**
     * Setter for <code>public.pets.type_id</code>.
     */
    public Pets setTypeId(Integer typeId) {
        this.typeId = typeId;
        return this;
    }

    /**
     * Getter for <code>public.pets.owner_id</code>.
     */
    public Integer getOwnerId() {
        return this.ownerId;
    }

    /**
     * Setter for <code>public.pets.owner_id</code>.
     */
    public Pets setOwnerId(Integer ownerId) {
        this.ownerId = ownerId;
        return this;
    }

    /**
     * Getter for <code>public.pets.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.pets.created_at</code>.
     */
    public Pets setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * Getter for <code>public.pets.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>public.pets.updated_at</code>.
     */
    public Pets setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Pets (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(birthDate);
        sb.append(", ").append(typeId);
        sb.append(", ").append(ownerId);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
