/*
 * This file is generated by jOOQ.
 */
package io.micronaut.example.petclinic.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Types implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private String        name;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public Types() {}

    public Types(Types value) {
        this.id = value.id;
        this.name = value.name;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public Types(
        Integer       id,
        String        name,
        LocalDateTime createdAt,
        LocalDateTime updatedAt
    ) {
        this.id = id;
        this.name = name;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>public.types.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.types.id</code>.
     */
    public Types setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.types.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.types.name</code>.
     */
    public Types setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>public.types.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.types.created_at</code>.
     */
    public Types setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * Getter for <code>public.types.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>public.types.updated_at</code>.
     */
    public Types setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Types (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
