/*
 * This file is generated by jOOQ.
 */
package io.micronaut.example.petclinic.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Types implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String  name;

    public Types() {}

    public Types(Types value) {
        this.id = value.id;
        this.name = value.name;
    }

    public Types(
        Integer id,
        String  name
    ) {
        this.id = id;
        this.name = name;
    }

    /**
     * Getter for <code>public.types.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.types.id</code>.
     */
    public Types setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.types.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.types.name</code>.
     */
    public Types setName(String name) {
        this.name = name;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Types (");

        sb.append(id);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
