/*
 * This file is generated by jOOQ.
 */
package io.micronaut.example.petclinic.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VetSpecialties implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer vetId;
    private Integer specialtyId;

    public VetSpecialties() {}

    public VetSpecialties(VetSpecialties value) {
        this.vetId = value.vetId;
        this.specialtyId = value.specialtyId;
    }

    public VetSpecialties(
        Integer vetId,
        Integer specialtyId
    ) {
        this.vetId = vetId;
        this.specialtyId = specialtyId;
    }

    /**
     * Getter for <code>public.vet_specialties.vet_id</code>.
     */
    public Integer getVetId() {
        return this.vetId;
    }

    /**
     * Setter for <code>public.vet_specialties.vet_id</code>.
     */
    public VetSpecialties setVetId(Integer vetId) {
        this.vetId = vetId;
        return this;
    }

    /**
     * Getter for <code>public.vet_specialties.specialty_id</code>.
     */
    public Integer getSpecialtyId() {
        return this.specialtyId;
    }

    /**
     * Setter for <code>public.vet_specialties.specialty_id</code>.
     */
    public VetSpecialties setSpecialtyId(Integer specialtyId) {
        this.specialtyId = specialtyId;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("VetSpecialties (");

        sb.append(vetId);
        sb.append(", ").append(specialtyId);

        sb.append(")");
        return sb.toString();
    }
}
