/*
 * This file is generated by jOOQ.
 */
package io.micronaut.example.petclinic.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Visits implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer   id;
    private Integer   petId;
    private LocalDate visitDate;
    private String    description;

    public Visits() {}

    public Visits(Visits value) {
        this.id = value.id;
        this.petId = value.petId;
        this.visitDate = value.visitDate;
        this.description = value.description;
    }

    public Visits(
        Integer   id,
        Integer   petId,
        LocalDate visitDate,
        String    description
    ) {
        this.id = id;
        this.petId = petId;
        this.visitDate = visitDate;
        this.description = description;
    }

    /**
     * Getter for <code>public.visits.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.visits.id</code>.
     */
    public Visits setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.visits.pet_id</code>.
     */
    public Integer getPetId() {
        return this.petId;
    }

    /**
     * Setter for <code>public.visits.pet_id</code>.
     */
    public Visits setPetId(Integer petId) {
        this.petId = petId;
        return this;
    }

    /**
     * Getter for <code>public.visits.visit_date</code>.
     */
    public LocalDate getVisitDate() {
        return this.visitDate;
    }

    /**
     * Setter for <code>public.visits.visit_date</code>.
     */
    public Visits setVisitDate(LocalDate visitDate) {
        this.visitDate = visitDate;
        return this;
    }

    /**
     * Getter for <code>public.visits.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>public.visits.description</code>.
     */
    public Visits setDescription(String description) {
        this.description = description;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Visits (");

        sb.append(id);
        sb.append(", ").append(petId);
        sb.append(", ").append(visitDate);
        sb.append(", ").append(description);

        sb.append(")");
        return sb.toString();
    }
}
