/*
 * This file is generated by jOOQ.
 */
package io.micronaut.example.petclinic;


import io.micronaut.example.petclinic.tables.Owners;
import io.micronaut.example.petclinic.tables.Pets;
import io.micronaut.example.petclinic.tables.Specialties;
import io.micronaut.example.petclinic.tables.Types;
import io.micronaut.example.petclinic.tables.Vets;
import io.micronaut.example.petclinic.tables.Visits;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index OWNERS_LAST_NAME = Internal.createIndex(DSL.name("owners_last_name"), Owners.OWNERS, new OrderField[] { Owners.OWNERS.LAST_NAME }, false);
    public static final Index PETS_NAME = Internal.createIndex(DSL.name("pets_name"), Pets.PETS, new OrderField[] { Pets.PETS.NAME }, false);
    public static final Index SPECIALTIES_NAME = Internal.createIndex(DSL.name("specialties_name"), Specialties.SPECIALTIES, new OrderField[] { Specialties.SPECIALTIES.NAME }, false);
    public static final Index TYPES_NAME = Internal.createIndex(DSL.name("types_name"), Types.TYPES, new OrderField[] { Types.TYPES.NAME }, false);
    public static final Index VETS_LAST_NAME = Internal.createIndex(DSL.name("vets_last_name"), Vets.VETS, new OrderField[] { Vets.VETS.LAST_NAME }, false);
    public static final Index VISITS_PET_ID = Internal.createIndex(DSL.name("visits_pet_id"), Visits.VISITS, new OrderField[] { Visits.VISITS.PET_ID }, false);
}
