/*
 * This file is generated by jOOQ.
 */
package io.micronaut.example.petclinic;


import io.micronaut.example.petclinic.tables.Owners;
import io.micronaut.example.petclinic.tables.Pets;
import io.micronaut.example.petclinic.tables.Specialties;
import io.micronaut.example.petclinic.tables.Types;
import io.micronaut.example.petclinic.tables.VetSpecialties;
import io.micronaut.example.petclinic.tables.Vets;
import io.micronaut.example.petclinic.tables.Visits;
import io.micronaut.example.petclinic.tables.records.OwnersRecord;
import io.micronaut.example.petclinic.tables.records.PetsRecord;
import io.micronaut.example.petclinic.tables.records.SpecialtiesRecord;
import io.micronaut.example.petclinic.tables.records.TypesRecord;
import io.micronaut.example.petclinic.tables.records.VetSpecialtiesRecord;
import io.micronaut.example.petclinic.tables.records.VetsRecord;
import io.micronaut.example.petclinic.tables.records.VisitsRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<OwnersRecord> OWNERS_PKEY = Internal.createUniqueKey(Owners.OWNERS, DSL.name("owners_pkey"), new TableField[] { Owners.OWNERS.ID }, true);
    public static final UniqueKey<PetsRecord> PETS_PKEY = Internal.createUniqueKey(Pets.PETS, DSL.name("pets_pkey"), new TableField[] { Pets.PETS.ID }, true);
    public static final UniqueKey<SpecialtiesRecord> SPECIALTIES_PKEY = Internal.createUniqueKey(Specialties.SPECIALTIES, DSL.name("specialties_pkey"), new TableField[] { Specialties.SPECIALTIES.ID }, true);
    public static final UniqueKey<TypesRecord> TYPES_PKEY = Internal.createUniqueKey(Types.TYPES, DSL.name("types_pkey"), new TableField[] { Types.TYPES.ID }, true);
    public static final UniqueKey<VetsRecord> VETS_PKEY = Internal.createUniqueKey(Vets.VETS, DSL.name("vets_pkey"), new TableField[] { Vets.VETS.ID }, true);
    public static final UniqueKey<VisitsRecord> VISITS_PKEY = Internal.createUniqueKey(Visits.VISITS, DSL.name("visits_pkey"), new TableField[] { Visits.VISITS.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<PetsRecord, OwnersRecord> PETS__FK_PETS_OWNERS = Internal.createForeignKey(Pets.PETS, DSL.name("fk_pets_owners"), new TableField[] { Pets.PETS.OWNER_ID }, Keys.OWNERS_PKEY, new TableField[] { Owners.OWNERS.ID }, true);
    public static final ForeignKey<PetsRecord, TypesRecord> PETS__FK_PETS_TYPES = Internal.createForeignKey(Pets.PETS, DSL.name("fk_pets_types"), new TableField[] { Pets.PETS.TYPE_ID }, Keys.TYPES_PKEY, new TableField[] { Types.TYPES.ID }, true);
    public static final ForeignKey<VetSpecialtiesRecord, SpecialtiesRecord> VET_SPECIALTIES__FK_VET_SPECIALTIES_SPECIALTIES = Internal.createForeignKey(VetSpecialties.VET_SPECIALTIES, DSL.name("fk_vet_specialties_specialties"), new TableField[] { VetSpecialties.VET_SPECIALTIES.SPECIALTY_ID }, Keys.SPECIALTIES_PKEY, new TableField[] { Specialties.SPECIALTIES.ID }, true);
    public static final ForeignKey<VetSpecialtiesRecord, VetsRecord> VET_SPECIALTIES__FK_VET_SPECIALTIES_VETS = Internal.createForeignKey(VetSpecialties.VET_SPECIALTIES, DSL.name("fk_vet_specialties_vets"), new TableField[] { VetSpecialties.VET_SPECIALTIES.VET_ID }, Keys.VETS_PKEY, new TableField[] { Vets.VETS.ID }, true);
    public static final ForeignKey<VisitsRecord, PetsRecord> VISITS__FK_VISITS_PETS = Internal.createForeignKey(Visits.VISITS, DSL.name("fk_visits_pets"), new TableField[] { Visits.VISITS.PET_ID }, Keys.PETS_PKEY, new TableField[] { Pets.PETS.ID }, true);
}
