/*
 * This file is generated by jOOQ.
 */
package io.micronaut.example.petclinic;


import io.micronaut.example.petclinic.tables.Owners;
import io.micronaut.example.petclinic.tables.Pets;
import io.micronaut.example.petclinic.tables.Specialties;
import io.micronaut.example.petclinic.tables.Types;
import io.micronaut.example.petclinic.tables.VetSpecialties;
import io.micronaut.example.petclinic.tables.Vets;
import io.micronaut.example.petclinic.tables.Visits;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.owners</code>.
     */
    public final Owners OWNERS = Owners.OWNERS;

    /**
     * The table <code>public.pets</code>.
     */
    public final Pets PETS = Pets.PETS;

    /**
     * The table <code>public.specialties</code>.
     */
    public final Specialties SPECIALTIES = Specialties.SPECIALTIES;

    /**
     * The table <code>public.types</code>.
     */
    public final Types TYPES = Types.TYPES;

    /**
     * The table <code>public.vet_specialties</code>.
     */
    public final VetSpecialties VET_SPECIALTIES = VetSpecialties.VET_SPECIALTIES;

    /**
     * The table <code>public.vets</code>.
     */
    public final Vets VETS = Vets.VETS;

    /**
     * The table <code>public.visits</code>.
     */
    public final Visits VISITS = Visits.VISITS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Owners.OWNERS,
            Pets.PETS,
            Specialties.SPECIALTIES,
            Types.TYPES,
            VetSpecialties.VET_SPECIALTIES,
            Vets.VETS,
            Visits.VISITS
        );
    }
}
