/*
 * This file is generated by jOOQ.
 */
package io.micronaut.example.petclinic.tables;


import io.micronaut.example.petclinic.Indexes;
import io.micronaut.example.petclinic.Keys;
import io.micronaut.example.petclinic.Public;
import io.micronaut.example.petclinic.tables.records.TypesRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Types extends TableImpl<TypesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.types</code>
     */
    public static final Types TYPES = new Types();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TypesRecord> getRecordType() {
        return TypesRecord.class;
    }

    /**
     * The column <code>public.types.id</code>.
     */
    public final TableField<TypesRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.types.name</code>.
     */
    public final TableField<TypesRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(80).nullable(false), this, "");

    /**
     * The column <code>public.types.created_at</code>.
     */
    public final TableField<TypesRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("CURRENT_DATE", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.types.updated_at</code>.
     */
    public final TableField<TypesRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("CURRENT_DATE", SQLDataType.LOCALDATETIME)), this, "");

    private Types(Name alias, Table<TypesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Types(Name alias, Table<TypesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.types</code> table reference
     */
    public Types(String alias) {
        this(DSL.name(alias), TYPES);
    }

    /**
     * Create an aliased <code>public.types</code> table reference
     */
    public Types(Name alias) {
        this(alias, TYPES);
    }

    /**
     * Create a <code>public.types</code> table reference
     */
    public Types() {
        this(DSL.name("types"), null);
    }

    public <O extends Record> Types(Table<O> child, ForeignKey<O, TypesRecord> key) {
        super(child, key, TYPES);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.TYPES_NAME);
    }

    @Override
    public Identity<TypesRecord, Integer> getIdentity() {
        return (Identity<TypesRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<TypesRecord> getPrimaryKey() {
        return Keys.TYPES_PKEY;
    }

    @Override
    public Types as(String alias) {
        return new Types(DSL.name(alias), this);
    }

    @Override
    public Types as(Name alias) {
        return new Types(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Types rename(String name) {
        return new Types(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Types rename(Name name) {
        return new Types(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
