/*
 * This file is generated by jOOQ.
 */
package io.micronaut.example.petclinic.tables;


import io.micronaut.example.petclinic.Indexes;
import io.micronaut.example.petclinic.Keys;
import io.micronaut.example.petclinic.Public;
import io.micronaut.example.petclinic.tables.records.VisitsRecord;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Visits extends TableImpl<VisitsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.visits</code>
     */
    public static final Visits VISITS = new Visits();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VisitsRecord> getRecordType() {
        return VisitsRecord.class;
    }

    /**
     * The column <code>public.visits.id</code>.
     */
    public final TableField<VisitsRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.visits.pet_id</code>.
     */
    public final TableField<VisitsRecord, Integer> PET_ID = createField(DSL.name("pet_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.visits.visit_date</code>.
     */
    public final TableField<VisitsRecord, LocalDate> VISIT_DATE = createField(DSL.name("visit_date"), SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>public.visits.description</code>.
     */
    public final TableField<VisitsRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.visits.created_at</code>.
     */
    public final TableField<VisitsRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("CURRENT_DATE", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.visits.updated_at</code>.
     */
    public final TableField<VisitsRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("CURRENT_DATE", SQLDataType.LOCALDATETIME)), this, "");

    private Visits(Name alias, Table<VisitsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Visits(Name alias, Table<VisitsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.visits</code> table reference
     */
    public Visits(String alias) {
        this(DSL.name(alias), VISITS);
    }

    /**
     * Create an aliased <code>public.visits</code> table reference
     */
    public Visits(Name alias) {
        this(alias, VISITS);
    }

    /**
     * Create a <code>public.visits</code> table reference
     */
    public Visits() {
        this(DSL.name("visits"), null);
    }

    public <O extends Record> Visits(Table<O> child, ForeignKey<O, VisitsRecord> key) {
        super(child, key, VISITS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.VISITS_PET_ID);
    }

    @Override
    public Identity<VisitsRecord, Integer> getIdentity() {
        return (Identity<VisitsRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<VisitsRecord> getPrimaryKey() {
        return Keys.VISITS_PKEY;
    }

    @Override
    public List<ForeignKey<VisitsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.VISITS__FK_VISITS_PETS);
    }

    private transient Pets _pets;

    public Pets pets() {
        if (_pets == null)
            _pets = new Pets(this, Keys.VISITS__FK_VISITS_PETS);

        return _pets;
    }

    @Override
    public Visits as(String alias) {
        return new Visits(DSL.name(alias), this);
    }

    @Override
    public Visits as(Name alias) {
        return new Visits(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Visits rename(String name) {
        return new Visits(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Visits rename(Name name) {
        return new Visits(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Integer, LocalDate, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
