/*
 * This file is generated by jOOQ.
 */
package io.micronaut.example.petclinic.tables.records;


import io.micronaut.example.petclinic.tables.Owners;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OwnersRecord extends UpdatableRecordImpl<OwnersRecord> implements Record8<Integer, String, String, String, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.owners.id</code>.
     */
    public OwnersRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.owners.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.owners.first_name</code>.
     */
    public OwnersRecord setFirstName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.owners.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.owners.last_name</code>.
     */
    public OwnersRecord setLastName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.owners.last_name</code>.
     */
    public String getLastName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.owners.address</code>.
     */
    public OwnersRecord setAddress(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.owners.address</code>.
     */
    public String getAddress() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.owners.city</code>.
     */
    public OwnersRecord setCity(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.owners.city</code>.
     */
    public String getCity() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.owners.telephone</code>.
     */
    public OwnersRecord setTelephone(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.owners.telephone</code>.
     */
    public String getTelephone() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.owners.created_at</code>.
     */
    public OwnersRecord setCreatedAt(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.owners.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.owners.updated_at</code>.
     */
    public OwnersRecord setUpdatedAt(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.owners.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, String, String, String, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, String, String, String, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Owners.OWNERS.ID;
    }

    @Override
    public Field<String> field2() {
        return Owners.OWNERS.FIRST_NAME;
    }

    @Override
    public Field<String> field3() {
        return Owners.OWNERS.LAST_NAME;
    }

    @Override
    public Field<String> field4() {
        return Owners.OWNERS.ADDRESS;
    }

    @Override
    public Field<String> field5() {
        return Owners.OWNERS.CITY;
    }

    @Override
    public Field<String> field6() {
        return Owners.OWNERS.TELEPHONE;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return Owners.OWNERS.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return Owners.OWNERS.UPDATED_AT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getFirstName();
    }

    @Override
    public String component3() {
        return getLastName();
    }

    @Override
    public String component4() {
        return getAddress();
    }

    @Override
    public String component5() {
        return getCity();
    }

    @Override
    public String component6() {
        return getTelephone();
    }

    @Override
    public LocalDateTime component7() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component8() {
        return getUpdatedAt();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getFirstName();
    }

    @Override
    public String value3() {
        return getLastName();
    }

    @Override
    public String value4() {
        return getAddress();
    }

    @Override
    public String value5() {
        return getCity();
    }

    @Override
    public String value6() {
        return getTelephone();
    }

    @Override
    public LocalDateTime value7() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value8() {
        return getUpdatedAt();
    }

    @Override
    public OwnersRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public OwnersRecord value2(String value) {
        setFirstName(value);
        return this;
    }

    @Override
    public OwnersRecord value3(String value) {
        setLastName(value);
        return this;
    }

    @Override
    public OwnersRecord value4(String value) {
        setAddress(value);
        return this;
    }

    @Override
    public OwnersRecord value5(String value) {
        setCity(value);
        return this;
    }

    @Override
    public OwnersRecord value6(String value) {
        setTelephone(value);
        return this;
    }

    @Override
    public OwnersRecord value7(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public OwnersRecord value8(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public OwnersRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, LocalDateTime value7, LocalDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OwnersRecord
     */
    public OwnersRecord() {
        super(Owners.OWNERS);
    }

    /**
     * Create a detached, initialised OwnersRecord
     */
    public OwnersRecord(Integer id, String firstName, String lastName, String address, String city, String telephone, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Owners.OWNERS);

        setId(id);
        setFirstName(firstName);
        setLastName(lastName);
        setAddress(address);
        setCity(city);
        setTelephone(telephone);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
    }

    /**
     * Create a detached, initialised OwnersRecord
     */
    public OwnersRecord(io.micronaut.example.petclinic.tables.pojos.Owners value) {
        super(Owners.OWNERS);

        if (value != null) {
            setId(value.getId());
            setFirstName(value.getFirstName());
            setLastName(value.getLastName());
            setAddress(value.getAddress());
            setCity(value.getCity());
            setTelephone(value.getTelephone());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
        }
    }
}
