/*
 * This file is generated by jOOQ.
 */
package io.micronaut.example.petclinic.tables.records;


import io.micronaut.example.petclinic.tables.Specialties;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpecialtiesRecord extends UpdatableRecordImpl<SpecialtiesRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.specialties.id</code>.
     */
    public SpecialtiesRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.specialties.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.specialties.name</code>.
     */
    public SpecialtiesRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.specialties.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Specialties.SPECIALTIES.ID;
    }

    @Override
    public Field<String> field2() {
        return Specialties.SPECIALTIES.NAME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public SpecialtiesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public SpecialtiesRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public SpecialtiesRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SpecialtiesRecord
     */
    public SpecialtiesRecord() {
        super(Specialties.SPECIALTIES);
    }

    /**
     * Create a detached, initialised SpecialtiesRecord
     */
    public SpecialtiesRecord(Integer id, String name) {
        super(Specialties.SPECIALTIES);

        setId(id);
        setName(name);
    }

    /**
     * Create a detached, initialised SpecialtiesRecord
     */
    public SpecialtiesRecord(io.micronaut.example.petclinic.tables.pojos.Specialties value) {
        super(Specialties.SPECIALTIES);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
        }
    }
}
