/*
 * This file is generated by jOOQ.
 */
package io.micronaut.example.petclinic.tables.records;


import io.micronaut.example.petclinic.tables.Specialties;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpecialtiesRecord extends UpdatableRecordImpl<SpecialtiesRecord> implements Record4<Integer, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.specialties.id</code>.
     */
    public SpecialtiesRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.specialties.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.specialties.name</code>.
     */
    public SpecialtiesRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.specialties.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.specialties.created_at</code>.
     */
    public SpecialtiesRecord setCreatedAt(LocalDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.specialties.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.specialties.updated_at</code>.
     */
    public SpecialtiesRecord setUpdatedAt(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.specialties.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Specialties.SPECIALTIES.ID;
    }

    @Override
    public Field<String> field2() {
        return Specialties.SPECIALTIES.NAME;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return Specialties.SPECIALTIES.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Specialties.SPECIALTIES.UPDATED_AT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public LocalDateTime component3() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component4() {
        return getUpdatedAt();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public LocalDateTime value3() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value4() {
        return getUpdatedAt();
    }

    @Override
    public SpecialtiesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public SpecialtiesRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public SpecialtiesRecord value3(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public SpecialtiesRecord value4(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public SpecialtiesRecord values(Integer value1, String value2, LocalDateTime value3, LocalDateTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SpecialtiesRecord
     */
    public SpecialtiesRecord() {
        super(Specialties.SPECIALTIES);
    }

    /**
     * Create a detached, initialised SpecialtiesRecord
     */
    public SpecialtiesRecord(Integer id, String name, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Specialties.SPECIALTIES);

        setId(id);
        setName(name);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
    }

    /**
     * Create a detached, initialised SpecialtiesRecord
     */
    public SpecialtiesRecord(io.micronaut.example.petclinic.tables.pojos.Specialties value) {
        super(Specialties.SPECIALTIES);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
        }
    }
}
