/*
 * This file is generated by jOOQ.
 */
package io.micronaut.example.petclinic.tables.records;


import io.micronaut.example.petclinic.tables.Types;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TypesRecord extends UpdatableRecordImpl<TypesRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.types.id</code>.
     */
    public TypesRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.types.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.types.name</code>.
     */
    public TypesRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.types.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Types.TYPES.ID;
    }

    @Override
    public Field<String> field2() {
        return Types.TYPES.NAME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public TypesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TypesRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public TypesRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TypesRecord
     */
    public TypesRecord() {
        super(Types.TYPES);
    }

    /**
     * Create a detached, initialised TypesRecord
     */
    public TypesRecord(Integer id, String name) {
        super(Types.TYPES);

        setId(id);
        setName(name);
    }

    /**
     * Create a detached, initialised TypesRecord
     */
    public TypesRecord(io.micronaut.example.petclinic.tables.pojos.Types value) {
        super(Types.TYPES);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
        }
    }
}
