/*
 * This file is generated by jOOQ.
 */
package io.micronaut.example.petclinic.tables.records;


import io.micronaut.example.petclinic.tables.VetSpecialties;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VetSpecialtiesRecord extends TableRecordImpl<VetSpecialtiesRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.vet_specialties.vet_id</code>.
     */
    public VetSpecialtiesRecord setVetId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.vet_specialties.vet_id</code>.
     */
    public Integer getVetId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.vet_specialties.specialty_id</code>.
     */
    public VetSpecialtiesRecord setSpecialtyId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.vet_specialties.specialty_id</code>.
     */
    public Integer getSpecialtyId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return VetSpecialties.VET_SPECIALTIES.VET_ID;
    }

    @Override
    public Field<Integer> field2() {
        return VetSpecialties.VET_SPECIALTIES.SPECIALTY_ID;
    }

    @Override
    public Integer component1() {
        return getVetId();
    }

    @Override
    public Integer component2() {
        return getSpecialtyId();
    }

    @Override
    public Integer value1() {
        return getVetId();
    }

    @Override
    public Integer value2() {
        return getSpecialtyId();
    }

    @Override
    public VetSpecialtiesRecord value1(Integer value) {
        setVetId(value);
        return this;
    }

    @Override
    public VetSpecialtiesRecord value2(Integer value) {
        setSpecialtyId(value);
        return this;
    }

    @Override
    public VetSpecialtiesRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VetSpecialtiesRecord
     */
    public VetSpecialtiesRecord() {
        super(VetSpecialties.VET_SPECIALTIES);
    }

    /**
     * Create a detached, initialised VetSpecialtiesRecord
     */
    public VetSpecialtiesRecord(Integer vetId, Integer specialtyId) {
        super(VetSpecialties.VET_SPECIALTIES);

        setVetId(vetId);
        setSpecialtyId(specialtyId);
    }

    /**
     * Create a detached, initialised VetSpecialtiesRecord
     */
    public VetSpecialtiesRecord(io.micronaut.example.petclinic.tables.pojos.VetSpecialties value) {
        super(VetSpecialties.VET_SPECIALTIES);

        if (value != null) {
            setVetId(value.getVetId());
            setSpecialtyId(value.getSpecialtyId());
        }
    }
}
