/*
 * This file is generated by jOOQ.
 */
package io.micronaut.example.petclinic.tables.records;


import io.micronaut.example.petclinic.tables.VetSpecialties;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VetSpecialtiesRecord extends TableRecordImpl<VetSpecialtiesRecord> implements Record4<Integer, Integer, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.vet_specialties.vet_id</code>.
     */
    public VetSpecialtiesRecord setVetId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.vet_specialties.vet_id</code>.
     */
    public Integer getVetId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.vet_specialties.specialty_id</code>.
     */
    public VetSpecialtiesRecord setSpecialtyId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.vet_specialties.specialty_id</code>.
     */
    public Integer getSpecialtyId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.vet_specialties.created_at</code>.
     */
    public VetSpecialtiesRecord setCreatedAt(LocalDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.vet_specialties.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.vet_specialties.updated_at</code>.
     */
    public VetSpecialtiesRecord setUpdatedAt(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.vet_specialties.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, Integer, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return VetSpecialties.VET_SPECIALTIES.VET_ID;
    }

    @Override
    public Field<Integer> field2() {
        return VetSpecialties.VET_SPECIALTIES.SPECIALTY_ID;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return VetSpecialties.VET_SPECIALTIES.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return VetSpecialties.VET_SPECIALTIES.UPDATED_AT;
    }

    @Override
    public Integer component1() {
        return getVetId();
    }

    @Override
    public Integer component2() {
        return getSpecialtyId();
    }

    @Override
    public LocalDateTime component3() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component4() {
        return getUpdatedAt();
    }

    @Override
    public Integer value1() {
        return getVetId();
    }

    @Override
    public Integer value2() {
        return getSpecialtyId();
    }

    @Override
    public LocalDateTime value3() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value4() {
        return getUpdatedAt();
    }

    @Override
    public VetSpecialtiesRecord value1(Integer value) {
        setVetId(value);
        return this;
    }

    @Override
    public VetSpecialtiesRecord value2(Integer value) {
        setSpecialtyId(value);
        return this;
    }

    @Override
    public VetSpecialtiesRecord value3(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public VetSpecialtiesRecord value4(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public VetSpecialtiesRecord values(Integer value1, Integer value2, LocalDateTime value3, LocalDateTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VetSpecialtiesRecord
     */
    public VetSpecialtiesRecord() {
        super(VetSpecialties.VET_SPECIALTIES);
    }

    /**
     * Create a detached, initialised VetSpecialtiesRecord
     */
    public VetSpecialtiesRecord(Integer vetId, Integer specialtyId, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(VetSpecialties.VET_SPECIALTIES);

        setVetId(vetId);
        setSpecialtyId(specialtyId);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
    }

    /**
     * Create a detached, initialised VetSpecialtiesRecord
     */
    public VetSpecialtiesRecord(io.micronaut.example.petclinic.tables.pojos.VetSpecialties value) {
        super(VetSpecialties.VET_SPECIALTIES);

        if (value != null) {
            setVetId(value.getVetId());
            setSpecialtyId(value.getSpecialtyId());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
        }
    }
}
